/* Modelagem Básica 
ENTIDADE = TABELA
CAMPOS OU REGISTROS = ATRIBUTOS */

CLIENTE
	NOME - CARACTER(30)
	CPF - NUUMERICO(11)
	EMAIL - CARACTER(30)
	TELEFONE - CARACTER(30)
	ENDERECO - CARACTER(100)
	SEXO - CARACTER(1)


/* PROCESSOS DE MODELAGEM */

/* FASE 01 E FASE 02 - AD ADM DE DADOS */
MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */
MODELAGEM FÍSICA - SCRIPSTS DE BANCO

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO O BANCO DE DADOS */
CREATE DATABASE EXEMPLO;
CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */ 
USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES */
CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO */
SHOW TABLES;

/* DECOBRINDO COMO E UMA ESTRUTURA DE UMA TABELA */
DESC CLIENTE;


/* SINTAXE BASICA DE INSERCAO - INSERT INTO TABELA ...;*/
/* FORMA 01 -EXCLUINDO AS COLUNAS */ 
INSERT INTO CLIENTE VALUES('JOAO', 'M', 'JOAO@GMAIL.COM', 988638273, '22923110', 'MARIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('CELIA', 'F', 'CELIA@GMAIL.COM', 541521456, '25078869', 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('JORGE', 'M', NULL, 885755896, '58748895', 'OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 02 - COLOCANDO AS COLUNAS */
INSERT INTO CLIENTE(NOME, SEXO, ENDERECO, TELEFONE, CPF)
	VALUES('LILIAN', 'F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', '947785696', 887774856);

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */
INSERT INTO CLIENTE VALUES 
							('ANA', 'F', 'ANA@GLOBO.COM', 85548962, '548556985', 'PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
							('CARLA', 'F', 'CARLA@TERRATI.COM', 7745828, '66587458', 'CAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');


/* O COMANDO SELECT 
SELECAO, PROJECAO E JUNCAO
*/ 
SELECT NOW();
SELECT 'KEPLIN SOUSA';
SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */
SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;
SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;
SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

/* APENAS PARA FINS ACADEMICOS */
SELECT * FROM CLIENTE;


/* FILTRANDO */ 
SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'F'; 

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';


/* UTILIZABDO O LIKE */
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

/* CARACTER CORINGA % -> QUALQUER COISA */
SELECT NOME, SEXO FROM CLIENTE 
WHERE ENDERECO LIKE '%RJ';


/* OPERADORES LÓGICOS */
-- OR - OU
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'M' OR ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'F' OR ENDERECO LIKE '%ESTACIO';

-- AND - E 
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'M' AND ENDERECO LIKE '%ESTACIO';


/* COUNT(*), GROUP BY, PERFORMANCE COM OPERADORES LÓGICOS */
-- CONTANDO OS REGISTROS DE UMA TABELA
SELECT COUNT(*) FROM CLIENTE;

/* OPERADOR GROUP BY */
SELECT SEXO, COUNT(*)
FROM CLIENTE
GROUP BY SEXO;


/* FILTRANDO VALORES NULOS */ 
/* IS OU IS NOT NULL */
SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NULL;

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NOT NULL;


/* UTILIZANDO O UPDATE PARA ATUALIZAR VALORES */ 
SELECT NOME, EMAIL
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'LILIAN@HOTMAIL.COM'
WHERE NOME = 'LILIAN';

UPDATE CLIENTE
SET EMAIL = 'JORGE@HOTMAIL.COM'
WHERE NOME = 'JORGE';


/* COMMIT E ROLLBACK */

/* DELETANDO REGISTROS COM A CLAUSULA DELETE */ 
DELETE FROM CLIENTE;

SELECT COUNT(*) FROM CLIENTE;

DELETE FROM CLIENTE 
WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE;


/* ENTRANDO COM MAIS TELEFONES */ 

UPDATE CLIENTE
SET TELEFONE = '97865434'
WHERE NOME = 'JOAO';

SELECT * FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE 
GROUP BY SEXO;


SELECT ENDERECO, COUNT(*) FROM CLIENTE 
GROUP BY ENDERECO;


/* COMO PETER CHEN CRIOU O MODELO DE ENTIDADE E RELACIONAMENTO, O MER, FORAM CRIADAS FORMAS NORMAIS, QUE SÃO DIRETRIZES PARA APLICAR EM MODELAGEM DE AMBIENTES OLTP OU AMBIENTES TRANSACIONAIS DE BANCO DE DADOS.

HOJE TEMOS MAIS DO QUE 3 FORMAS NORMAIS, MAS AO NORMALIZARMOS UM BANCO ATE A SU TERCEIRA FORMA, É O SUFICIENTE PARA TER UM TRABALHO LIMPO E LIVRE DE ERROS. */ 


/* PRIMEIRA FORMA NORMAL */ 
/* 

1 - TODO CAMPO VETORIZADO SE TORNARAR OUTRA TABELA
		[AMARELO, AZUL, LARANJA, VERDE] -> VETOR CORES
		[KA, FIESTA, UNO, CIVIC] -> VETOR CARROS

2 - TODO CAMPO MULTIVALORADO SE TORNARAR OUTRA TABELA.
		QUANDO O CAMPO FOR DIVISIVEL 

3 - TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE TODO O REGISTRO COMO SENDO UNICO.
		ISSO É O QUE CHAMAMOS DE CHAVE PRIMARIA OU PRIMARY KEY. 
*/


/* CARDINALIDADE */ 
/* QUEM DEFINE A CARDINALIDADE É A REGRA DE NEGOCIOS */

/* PRIMEIRO ALGARISMO - OBRIGATORIEDADE
0 - NÃO OBRIGATORIO
1 - OBRIGATORIO

SEGUNDO ALGARISMO - CARDINALIDADE
1 - MAXIMO DE UM 
N - MAIS DE UM 
*/

CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M', 'F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(11) UNIQUE
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'COM', 'CEL'),
	NUMERO VARCHAR (11),
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);


/* ENDERECO - OBRIGATORIO 
CADASTRO DE SOMENTE UM.


TELEFONE - NÃO OBRIGATORIO 
CADASTRO DE UM, VARIOS OU NENHUM (OPCIONAL) */


/* CHAVE ESTRANGEIRA É A CHAVE PRIMARIA DE UMA TABELA QUE VAI ATÉ A OUTRA TABELA PARA FAZER REFERENCIA ENTRE REGISTROS */

/* EM RELACIONAMENTO 1x1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */

/* EM RELACIONAMENTOS 1 x N A CHAVE ESTRANGEIRA FICARA SEMPRE NA CARDINALIDADE N */

-- INSERINDO REGISTRO NA TABELA CLIENTE
INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAOA@IG.COM','76567587887');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','M','JCELIA@IG.COM','5767876889');

SELECT * FROM CLIENTE;
+-----------+--------+------+----------------+-------------+
| IDCLIENTE | NOME   | SEXO | EMAIL          | CPF         |
+-----------+--------+------+----------------+-------------+
|         1 | JOAO   | M    | JOAOA@IG.COM   | 76567587887 |
|         2 | CARLOS | M    | CARLOSA@IG.COM | 5464553466  |
|         3 | ANA    | F    | ANA@IG.COM     | 456545678   |
|         4 | CLARA  | F    | NULL           | 5687766856  |
|         5 | JORGE  | M    | JORGE@IG.COM   | 8756547688  |
|         6 | CELIA  | M    | JCELIA@IG.COM  | 5767876889  |
+-----------+--------+------+----------------+-------------+


-- INSERINDO REGISTRO NA TABELA ENDERECO
INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA PRES VARGAS','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO VALUES(NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',5);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','CENTRO','SAO PAULO','SP',5);

SELECT * FROM ENDERECO;

-- INSERINDO REGISTRO NA TABELA TELEFONE
INSERT INTO TELEFONE VALUES(NULL,'CEL','78458743',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','56576876',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','87866896',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','54768899',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','99667587',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','78989765',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99766676',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','66687899',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','89986668',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88687909',2);

SELECT * FROM TELEFONE;

/* SELECAO, PROJECAO E JUNCAO */

/* PROJECAO -> É TUDO O QUE VOCE QUER VER NA TELA */
SELECT NOW() AS DATA_ATUAL;

SELECT 2 + 2 AS SOMA;

/* SELECAO  -> É UM SUB CONJUNTO DO CONJUNTO TOTAL DE REGISTROS DE UMA TABELA 
A CLAUSULA DE SELECAO PE O WHERE*/

SELECT NOME, SEXO, EMAIL /* PROJECAO */
FROM CLIENTE /* ORIGEM */
WHERE SEXO = 'F'; /* SELECAO */

SELECT NUMERO  /* PROJECAO */
FROM TELEFONE /* ORIGEM */
WHERE TIPO = 'CEL' /* SELECAO */

/* JUNCAO -> JOIN */

SELECT NOME, EMAIL, IDCLIENTE 
FROM CLIENTE;

SELECT ID_CLIENTE, BAIRRO, CIDADE 
FROM ENDERECO;

/* NOME, SEXO, BAIRRO, CIDADE */
SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE 


SELECT NOME, SEXO, BAIRRO, CIDADE 
FROM CLIENTE 
INNER JOIN ENDERECO 
ON IDCLIENTE = ID_CLIENTE;

SELECT NOME, SEXO, BAIRRO, CIDADE 
FROM CLIENTE 
	INNER JOIN ENDERECO 
	ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'F';

/* NOME, SEXO, EMAIL, TIPO, NUMERO */
SELECT NOME, SEXO, EMAIL, TIPO, NUMERO 
FROM CLIENTE 
	INER JOIN TELEFONE  
	ON IDCLIENTE =  ID_CLIENTE;

/* NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO */

SELECT 
	C.NOME, 
	C.SEXO, 
	E.BAIRRO, 
	E.CIDADE, 
	T.TIPO, 
	T.NUMERO
FROM CLIENTE AS C
	INNER JOIN ENDERECO AS E
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE AS T
	ON C.IDCLIENTE = T.ID_CLIENTE;


/* 
	DML - DATA MANIPULATION LANGUAGE
	DDL - DATA DEFINITION LANGUAGE
	DCL - DATA CONTROL LANGUAGE
	TCL - TRANSACTION CONTROL LANGUAGE 
*/

/* INSERT */
INSERT INTO CLIENTE VALUES(NULL,'PAULA','M',NULL,'77437493');
INSERT INTO ENDERECO VALUES(NULL,'RUA JOAQUIM SILVA','ALVORADA','NITEROI','RJ',7);


/* FILTROS */
SELECT * FROM CLIENTE
WHERE SEXO = 'M';


/* UPDATE */
SELECT * FROM CLIENTE
WHERE IDCLIENTE = 7;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 7;


/* DELETE */ 
INSERT INTO CLIENTE VALUES(NULL,'XXX','M',NULL,'XXX');

SELECT * FROM CLIENTE
WHERE IDCLIENTE = 8;

DELETE FROM CLIENTE WHERE IDCLIENTE = 8;


/* 
  DDL - DATA DEFINITION LANGUAGE
*/

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_PRODUTO VARCHAR(30) NOT NULL,
	PRECO INT,
	FRETE FLOAT(10,2) NOT NULL
);

/* ALTER TABLE */

/* ALTERANDO O NOME DE UMA COLUNA - CHANGE */
ALTER TABLE PRODUTO
CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

DESC PRODUTO;

ALTER TABLE PRODUTO
CHANGE VALOR_UNITARIO VALOR_UNITARIO INT;

DESC PRODUTO;

/* MODIFY - ALTERANDO O TIPO */
ALTER TABLE PRODUTO
MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;

/* ADICIONANDO COLUNAS */
ALTER TABLE PRODUTO
ADD PESO FLOAT(10,2) NOT NULL;

/* APAGANDO UMA COLUNA */
ALTER TABLE PRODUTO
DROP COLUMN PESO;

/* ADICIONANDO UMA COLUNA NA ORDEM ESPECIFICA */
ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
AFTER NOME_PRODUTO;

ALTER TABLE PRODUTO
DROP COLUMN PESO;

ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
FIRST;












