/* Modelagem Básica 
ENTIDADE = TABELA
CAMPOS OU REGISTROS = ATRIBUTOS */

CLIENTE
	NOME - CARACTER(30)
	CPF - NUUMERICO(11)
	EMAIL - CARACTER(30)
	TELEFONE - CARACTER(30)
	ENDERECO - CARACTER(100)
	SEXO - CARACTER(1)


/* PROCESSOS DE MODELAGEM */

/* FASE 01 E FASE 02 - AD ADM DE DADOS */
MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */
MODELAGEM FÍSICA - SCRIPSTS DE BANCO

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO O BANCO DE DADOS */
CREATE DATABASE EXEMPLO;
CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */ 
USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES */
CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO */
SHOW TABLES;

/* DECOBRINDO COMO E UMA ESTRUTURA DE UMA TABELA */
DESC CLIENTE;


/* SINTAXE BASICA DE INSERCAO - INSERT INTO TABELA ...; */
/* FORMA 01 -EXCLUINDO AS COLUNAS */ 
INSERT INTO CLIENTE VALUES('JOAO', 'M', 'JOAO@GMAIL.COM', 988638273, '22923110', 'MARIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('CELIA', 'F', 'CELIA@GMAIL.COM', 541521456, '25078869', 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('JORGE', 'M', NULL, 885755896, '58748895', 'OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 02 - COLOCANDO AS COLUNAS */
INSERT INTO CLIENTE(NOME, SEXO, ENDERECO, TELEFONE, CPF)
	VALUES('LILIAN', 'F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', '947785696', 887774856);

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */
INSERT INTO CLIENTE VALUES 
							('ANA', 'F', 'ANA@GLOBO.COM', 85548962, '548556985', 'PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
							('CARLA', 'F', 'CARLA@TERRATI.COM', 7745828, '66587458', 'CAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');


/* O COMANDO SELECT 
SELECAO, PROJECAO E JUNCAO
*/ 
SELECT NOW();
SELECT 'KEPLIN SOUSA';
SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */
SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;
SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;
SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

/* APENAS PARA FINS ACADEMICOS */
SELECT * FROM CLIENTE;


/* FILTRANDO */ 
SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'F'; 

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';


/* UTILIZABDO O LIKE */
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

/* CARACTER CORINGA % -> QUALQUER COISA */
SELECT NOME, SEXO FROM CLIENTE 
WHERE ENDERECO LIKE '%RJ';


/* OPERADORES LÓGICOS */
-- OR - OU
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'M' OR ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'F' OR ENDERECO LIKE '%ESTACIO';

-- AND - E 
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'M' AND ENDERECO LIKE '%ESTACIO';


/* COUNT(*), GROUP BY, PERFORMANCE COM OPERADORES LÓGICOS */
-- CONTANDO OS REGISTROS DE UMA TABELA
SELECT COUNT(*) FROM CLIENTE;

/* OPERADOR GROUP BY */
SELECT SEXO, COUNT(*)
FROM CLIENTE
GROUP BY SEXO;






